# Generated by Django 5.0.6 on 2024-06-27 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('reg_no', models.PositiveIntegerField()),
                ('hostel_no', models.PositiveIntegerField()),
                ('room_no', models.CharField(max_length=10)),
                ('mess_in', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('meal_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('main_dish', models.CharField(max_length=100)),
                ('roti', models.BooleanField(default=False)),
                ('side_dish', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('fee_id', models.AutoField(primary_key=True, serialize=False)),
                ('in_date', models.DateField(blank=True, null=True)),
                ('out_date', models.DateField(blank=True, null=True)),
                ('fee_amount', models.FloatField()),
                ('student_reg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(max_length=10)),
                ('breakfast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakfast', to='supervisor.meals')),
                ('dinner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dinner', to='supervisor.meals')),
                ('lunch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lunch', to='supervisor.meals')),
            ],
        ),
    ]
