# Generated by Django 5.0.6 on 2024-06-30 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0003_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback_text', models.TextField(blank=True, null=True)),
                ('rating', models.CharField(choices=[('poor', 'Poor'), ('neutral', 'Neutral'), ('good', 'Good')], max_length=10)),
                ('student_reg_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
