# Generated by Django 5.0.6 on 2024-07-02 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0004_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='fee_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
